### ISSUE TITLE
Upgrade to flysystem v2

### ISSUE THREAD

**Issue by f3l1x** [contributte/flysystem#12]

**Comment by martenb** [comment]
any update here? there is already v3 out https://packagist.org/packages/league/flysystem

**Comment by f3l1x** [comment]
No updates ATM. Can you prepare v3?

**Comment by petrparolek** [comment]
I am preparing

**Comment by petrparolek** [comment]
done

**Comment by petrparolek** [comment]
could you test it @f3l1x  @martenb  please? I never have used this package.

**Comment by martenb** [comment]
@petrparolek ok, i will check it this week

**Comment by f3l1x** [comment]
Done https://github.com/contributte/flysystem/releases/tag/v0.3.0
